server:
  port: 8181

spring:
  application:
    name: jpa
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # none, create(tbl), update(edit), validate, create-drop
#    properties:
#      hibernate:
#        format_sql: true # P6SpySqlFormatter

# log level setting
logging:
  level:
    root: info
    com:
      spring:
        jpa: debug
    org:
      hibernate:
        SQL: debug